// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7JYuV3r0gVH4I5JVy04yRHXq-eCFpig',
    appId: '1:701781372474:web:7518f258ff6b95077b4f03',
    messagingSenderId: '701781372474',
    projectId: 'tournament-app-3f110',
    authDomain: 'tournament-app-3f110.firebaseapp.com',
    storageBucket: 'tournament-app-3f110.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXNNluIY2h_WdErHmHilFTXoPR1kccAHw',
    appId: '1:701781372474:android:625da09cf9ebe2297b4f03',
    messagingSenderId: '701781372474',
    projectId: 'tournament-app-3f110',
    storageBucket: 'tournament-app-3f110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh9x1QcgT9ss-0VmLVxNbVC0zDT1sNeSI',
    appId: '1:701781372474:ios:26e5264ed2d574f87b4f03',
    messagingSenderId: '701781372474',
    projectId: 'tournament-app-3f110',
    storageBucket: 'tournament-app-3f110.firebasestorage.app',
    iosBundleId: 'com.example.barberBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh9x1QcgT9ss-0VmLVxNbVC0zDT1sNeSI',
    appId: '1:701781372474:ios:26e5264ed2d574f87b4f03',
    messagingSenderId: '701781372474',
    projectId: 'tournament-app-3f110',
    storageBucket: 'tournament-app-3f110.firebasestorage.app',
    iosBundleId: 'com.example.barberBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo7JYuV3r0gVH4I5JVy04yRHXq-eCFpig',
    appId: '1:701781372474:web:1fb6d176af340eed7b4f03',
    messagingSenderId: '701781372474',
    projectId: 'tournament-app-3f110',
    authDomain: 'tournament-app-3f110.firebaseapp.com',
    storageBucket: 'tournament-app-3f110.firebasestorage.app',
  );
}
